# remove "version: ..." (obsolete)
name: iot-stack

services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks: [iotnet]

  nodered:
    build:
      context: ./nodered
      dockerfile: Dockerfile
    container_name: nodered
    restart: unless-stopped
    environment:
      - TZ=Europe/Zagreb
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
      - ./nodered/seed/flows.json:/seed/flows.json:ro
    command: ["/bin/sh","-lc",
      "chown -R node-red:node-red /data 2>/dev/null || true; \
       cp /seed/flows.json /data/flows.json; \
       chown node-red:node-red /data/flows.json 2>/dev/null || true; \
       exec npm start -- --userDir /data"
    ]
    depends_on:
      - mosquitto          # no health condition
    networks: [iotnet]

networks:
  iotnet:
    driver: bridge

volumes:
  nodered_data:
    driver: local

